# Generated by Django 6.0.2 on 2026-02-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_sociallinks_alter_about_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLinks',
            new_name='SocialLink',
        ),
    ]
